CREATE TABLE Usuarios (
    UsuarioID INT PRIMARY KEY IDENTITY(1,1),
    Nombre VARCHAR(50) NOT NULL,
    CorreoElectronico VARCHAR(100) NOT NULL,
    Contrase�a VARCHAR(50) NOT NULL,
    FechaRegistro DATETIME DEFAULT GETDATE()
);

-- Stored Procedure para Registro de Usuarios
CREATE PROCEDURE RegistrarUsuario
    @Nombre VARCHAR(50),
    @CorreoElectronico VARCHAR(100),
    @Contrase�a VARCHAR(50)
AS
BEGIN
    INSERT INTO Usuarios (Nombre, CorreoElectronico, Contrase�a)
    VALUES (@Nombre, @CorreoElectronico, @Contrase�a)
END;

------------------------------
CREATE TABLE QuichePalabrasFrases (
    PalabraFraseID INT PRIMARY KEY IDENTITY(1,1),
    PalabraFraseQuiche NVARCHAR(255) NOT NULL,
    TraduccionEspa�ol NVARCHAR(255) NOT NULL,
    FechaAgregacion DATETIME DEFAULT GETDATE(),
    UsuarioID INT,
    CONSTRAINT FK_Usuario_PalabraFrase FOREIGN KEY (UsuarioID) REFERENCES Usuarios(UsuarioID)
);

-- Trigger para Registro de Nuevas Palabras o Frases
CREATE TRIGGER RegistroPalabraFrase
ON QuichePalabrasFrases
AFTER INSERT
AS
BEGIN
    INSERT INTO EstadisticasPalabras (Palabra, CantidadConsultas, FechaEstadistica)
    SELECT i.TraduccionEspa�ol, 0, GETDATE()
    FROM inserted i
    WHERE NOT EXISTS (
        SELECT 1
        FROM EstadisticasPalabras
        WHERE Palabra = i.TraduccionEspa�ol
    )
END;

-------------------------

CREATE TABLE Consultas (
    ConsultaID INT PRIMARY KEY IDENTITY(1,1),
    UsuarioID INT,
    TextoConsulta NVARCHAR(MAX) NOT NULL,
    FechaConsulta DATETIME DEFAULT GETDATE(),
    IP VARCHAR(15), -- Suponiendo que la IP es almacenada en formato de texto
    CONSTRAINT FK_Usuario_Consulta FOREIGN KEY (UsuarioID) REFERENCES Usuarios(UsuarioID)
);

------------------------

CREATE TABLE NoEncontradas (
    NoEncontradaID INT PRIMARY KEY IDENTITY(1,1),
    PalabraFrase NVARCHAR(255) NOT NULL,
    FechaRegistro DATETIME DEFAULT GETDATE()
);

-----------------------------------------

CREATE TABLE EstadisticasPalabras (
    EstadisticaID INT PRIMARY KEY IDENTITY(1,1),
    Palabra NVARCHAR(255) NOT NULL,
    CantidadConsultas INT NOT NULL,
    FechaEstadistica DATETIME DEFAULT GETDATE()
);

-- Stored Procedure para Registrar Consulta y Actualizar Estadasticas
CREATE PROCEDURE RegistrarConsulta
    @UsuarioID INT,
    @TextoConsulta NVARCHAR(MAX),
    @IP VARCHAR(15)
AS
BEGIN
    INSERT INTO Consultas (UsuarioID, TextoConsulta, IP)
    VALUES (@UsuarioID, @TextoConsulta, @IP)

    UPDATE EstadisticasPalabras
    SET CantidadConsultas = CantidadConsultas + 1
    WHERE Palabra IN (SELECT TraduccionEspa�ol FROM QuichePalabrasFrases WHERE @TextoConsulta LIKE '%' + PalabraFraseQuiche + '%')
END;


----------------------insertar datos en tabla diccionario---

INSERT INTO QuichePalabrasFrases (PalabraFraseQuiche, TraduccionEspa�ol, UsuarioID)
VALUES
	('A',	'Muchacho, ni�o', 1),
	('Ab�',	'Hamaca',1),
	('Ab , ch�at',	'Catre',1),
	('Ab�a�q',	'Holl�n',1),
	('Ab�a�qchik�p', 'Milpi�s',1),
	('Ab�aj', 'Piedra',1), 
	('Ab��j', 'Mineral',1), 
	('Ab�ix','Milpa',1),
	('Achalal', 'Pariente, familiar',1), 
	('Achalalib�al','Hermanastro (a)',1), 
	('Achalalil k�aslemal','Vida familiar',1), 
	('Achalalxik', 'Parientes',1), 
	('Achalka�n', 'Concu�a',1), 
	('Achb�anoj','Adverbio',1),
	('Achb�axininem', 'Tira c�mica',1), 
	('Achb�i�aj, q�alajsab��l b�i�aj', 'Adjetivo',1), 
	('Acheqa�lenel', 'Paciente',1),
	('Achi','Hombre',1), 
	('Achi k�ulajil', 'Homosexual',1), 
	('Achi�al', 'Masculino',1),
	('Achi�l', 'Amigo',1), 
	('Achi�lanel', 'Escolta',1), 
	('Achi�lanem', 'Afiliado',1),
	('Achi�lib�', 'Compadres',1), 
	('Achib�il', 'Compa�ero (a), amigo (a)',1), 
	('Achib�ilanik, achib�ilanem', 'Acompa�ar',1),
	('Achijal', 'Masculino',1),
	('Achijil',	'Esposo',1), 
	('Achik�', 'Visi�n',1),
	('Achik�al tijonem', 'Educaci�n virtual',1), 
	('Achik�anem', 'So�ar, fantasia',1),
	('Achik�nem', 'Imaginaci�n',1), 
	('Achikowija�', 'Semen',1), 
	('Achixanik, achixanem', 'Celar',1),
	('Achixik',	'Celoso',1), 
	('Achji�','Concu�o',1),
	('Achochib��l', 'Direcci�n',1), 
	('Achochib��l',	'H�bitat',1),
	('Africa', '�frica',1), 
	('Africano', 'Africano',1),
	('Aj', 'Elote, cohete, ca�a de carrizo',1), 
	('Aj ab�yayala', 'Americano',1),
	('Aj eta�mab�alil k�aslem',	'Bi�logo',1),
	('Aj Europa', 'Europeo',1), 
	('Aj Francia', 'Franc�s',1),
	('Aj il', 'Responsable',1), 
	('Aj Italia', 'Italiano',1),
	('Aj jela� ch�awem', 'Lengua extranjera',1), 
	('Aj paxil kayala�', 'Guatemalteco',1),
	('Ajalib��l', 'Factor',1), 
	('Ajalk�walib��l', 'Adopci�n',1),
	('Ajanel', 'Carpintero',1), 
	('Ajatz�yaqb��l', 'Modista',1), 
	('Ajaw,ajawaxel', 'Dios',1),
	('Ajawan ib� xoqoje� k�utb�alil', 'G�nero y autoestima',1), 
	('Ajawb��l', 'Reino',1),
	('Ajb�anal kaxlanwa', 'Panadero',1), 
	('Ajb�anal wa',	'Cocinero (a)',1), 
	('Ajb�insal ch�ich�', 'Chofer',1), 
	('Ajch�ab��l', 'Cat�lico',1),
	('Ajch�aqaja� b�antajik', 'Cultura Occidental',1), 
	('Ajch�umil', 'Astr�nomo',1), 
	('Ajcha�al q�ayes', 'Bot�nico',1),
	('Ajchajil re tinimit',	'Polic�a, soldado',1),
	('Ajchak', 'Profesional',1), 
	('Ajchaq�e chak', 'Patr�n',1),
	('Ajchomsu�', 'Trompetista',1),
	('B�a', 'Taltuza',1),
	('B�ajb��l', 'Martillo',1), 
	('B�ajinik, b�ajinem', 'Clavar',1), 
	('B�alam', 'Jaguar, tigre',1), 
	('B�alkatinem, b�alkatinik', 'Rodar',1),
	('B�aluk', 'Cu�ado de hombre',1), 
	('B�anb��l', 'Molde',1),
	('B�anb��l chulaj', 'Letrina',1),
	('B�anb��l chuluj',	'Servicio sanitario',1),
	('B�anb��l k�ajkab�', 'Ingenio',1),
	('B�anb��l taqanib��l', 'Congreso',1), 
	('B�anb��l wa', 'Cocina',1), 
	('B�anb�alnik', 'Moldear',1), 
	('B�anb�l no�jwuj', 'Imprenta',1), 
	('B�anem', 'Predicado',1), 
	('B�anik, b�anonem, b�anonik', 'Hacer',1), 
	('B�anikil', 'Identidad',1),
	('B�anikil', 'Posicional',1), 
	('B�ankoyuq ch�ich�', 'Niobio',1),
	('B�anoj', 'Verbo',1), 
	('B�anojil', 'Verbal',1),
	('B�an�l taqanik', 'Diputado',1), 
	('B�anol tzij', 'Mentiroso',1), 
	('B�anom', 'Hecho B�anom','Artificial',1),
	('B�anom uk�u�xjastaq','Tecnecio',1), 
	('B�anowem','Acci�n',1),
	('B�antajik','Drama (obra de teatro)',1), 
	('B�antajik','Dignidad',1),
	('B�antajik b�anikil', 'Identidad cultural',1), 
	('B�antajik no�jk�aslemal','Valores culturales',1), 
	('B�antajik, wokaj k�aslemal','Cultura',1),
	('B�antajinik, kab�antajinik', 'Dramatizar,dramatiza',1), 
	('B�anub�eyal ilw�ch','�ptico',1),
	('B�anyal','Pragmatismo',1),
	('B�aq','Aguja, delgado, hueso',1), 
	('B�aq etz�b��l','Dado',1),
	('B�aq k�amatyo�jil','Tejido �seo',1), 
	('B�aq q�otz','P�mulo',1),
	('B�aq�tim tz�ib�awuj','Cuaderno de espiral',1), 
	('B�aqil k�ajk��s','Citoesqueleto',1),
	('B�aqil, ch�akul','Cuerpo',1),
	('B�aqilal','Esqueleto, vertebrado',1), 
	('B�aqilno�j', 'Paradigma',1),
	('B�aqiltzib�','Consonante',1),
	('B�aqonem, b�och�onem, b�aqonik','Restregar, frotar',1),
	('B�aqonik','Frotar, restregar',1), 
	('B�atz�','Hilo (de algod�n)',1), 
	('B�atz�im','Hilado',1), 
	('B�atz�inem, b�atz�inik','Hilar',1),
	('B�atz�om kamnaq','Momia',1), 
	('B�e','Camino',1),
	('B�ek','Ir',1), 
	('B�elejeb�','Nueve',1),
	('B�elejk�al','Ciento ochenta',1), 
	('B�elejlajk�al','Trescientos ochenta',1), 
	('B�elejlajq�o�','Siete mil seiscientos',1), 
	('B�elejlajuj','Diecinueve',1), 
	('B�elejq�o�','Tres mil seiscientos',1), 
	('B�enaq q�ij','Tarde',1),
	('B�enaq q�ij, uqajib�al q�ij','Atardecer',1), 
	('B�etz�ib�','Ortograf�a',1),
	('B�eyajel, q�axel, ajch�aqaja�','Extranjero, forastero',1), 
	('B�eyajem, b�eyajik','Viajar, pasear',1),
	('B�eyal k�u�xchak','M�todo de s�ntesis',1), 
	('B�eyal rech tijonik','M�todo de ense�anza',1),
	('B�eyal reta�maxik tzijonem','M�todo de aprendizaje de idiomas',1),
	('B�eyal ruk�utik ukab� ch�ab��l','M�todo para la ense�anza de segunda lengua',1),
	('B�eyal sik�itz�ib�anem','M�todos de lectoescritura',1), 
	('B�eyal solw�ch','M�todo de an�lisis',1),
	('B�e�al tijonik, b�eyal','M�todo',1), 
	('B�e�n','Enano',1),
	('B�e�nche�','Arbusto',1),
	('B�eelom','Marido, esposo',1), 
	('B�ijna�oj','Predicativo',1), 
	('B�ijnem','Sugerencia',1), 
	('B�ijnik','Sugerir',1),
	('B�iloj, rax kinaq�','Ejote',1), 
	('B�in�l tzij',	'Sem�ntica',1), 
	('B�inem juyub�','Alpinismo',1), 
	('B�inem, b�inik','Caminar',1), 
	('B�insanel ch�ich�','Piloto',1),
	('B�insanem','Tr�mite',1),
	('B�iq�b�anel silow�ch','Camar�grafo (de tele)',1), 
	('B�iq�onem','Tragado',1),
	('B�iq�onem b�iq�onik','Tragar',1),
	('B�iq�silowachib��l','C�mara de video, de televisi�n',1), 
	('B�iq�wachib��l','C�mara digital',1),
	('B�iqonem','Desgranando',1), 
	('B�iqonik, b�iqonem','Desgranar',1),
	('B�irb�itq�ajaj', 'Onda sonora, onda ac�stica',1), 
	('B�irirtab��l, xelayil','T�mpano',1),
	('B�isonem','Triste',1), 
	('B�itok, ilb��l, okib�al saq','Ventana',1),
	('B�ix','Canci�n, canto',1), 
	('B�ixajaw','Alabanza',1),
	('B�ixal','Melod�a',1), 
	('B�ixb��l','Cancionero',1),
	('B�ixik','Decir',1),
	('B�ixkil','Informe, Informativo',1), 
	('B�ixonel','Cantante',1),
	('B�ixonik','Cantar',1),	
	('B�i�aj','Nombre',1), 
	('B�i�aj, b�i�ajnem','Sustantivo',1),
	('B�i�ajnel','Sustantivizador',1), 
	('B�i�ajnem','Sustantivos',1), 
	('B�i�nik','Nombrar',1), 
	('B�ochk�ulajil','Noviazgo',1), 
	('B�oko�','Chimaltenango',1),
	('B�okob�, tatb�em','Escudo',1),
	('B�ol, xax ch�ich�','Lata',1), 
	('B�olaj','Trozo',1),
	('B�olajch�ich�, yuquyik ch�ich�','Ferrocarril',1),
	('B�olb��l','Rodillos',1), 
	('B�olb�ik, b�olob�il','Cil�ndrico',1),
	('B�olob�ik','Cilindro',1),
	('Cha�b��l','Filtro (de aceite)',1),
	('Cha�b��l ch�j','Filtro (para pantalla de computadora',1), 
	('Cha�nel','Jurado',1),
	('Cha�t�ltijonem','Educaci�n no Formal',1), 
	('Cha�yinik, kchayinik','Votar, vota',1),
	('Chab��l','Coladera',1), 
	('Chab�ana jun toq�ob�','Por favor',1),
	('Chab�ij chwe','Dec�melo',1),
	('Chachal','Collar',1),
	('Chaj','Gris, cenizo, ceniza, ocote, pino',1), 
	('Chajim q�ij','Feriado',1),
	('Chajinb��l yawab�','Enfermer�a',1), 
	('Chajinel','Polic�a',1),
	('Chajinel amaq�','Ej�rcito, soldado',1), 
	('Chajinel yawab�, ajyab�','Enfermera',1), 
	('Chajinik','Cuidar, proteger',1), 
	('Chajinsanem','Cremaci�n',1),
	('Chajitalil, jikomal','Seguridad',1),
	('Chajnel','F�sforo (como elemento)',1), 
	('Chak','Trabajo',1),
	('Chak chuqe kamulinem','Actividades y ejercicios',1), 
	('Chak wokajtaqanik','Legislaci�n laboral',1), 
	('Chak xuquje� tikojilil','Trabajo y productividad',1), 
	('Chak�amalo chwe','Tr�emelo',1),
	('Chakach','Canasta',1), 
	('Chak�ch potz�','Baloncesto',1),
	('Chak�ch, ch�uy, ch�ajo�n','Mech�n (como de jirafa)',1), 
	('Chakalb��l ch�ich�','Parqueo',1),
	('Chakub��l','�tiles de trabajo, herramientas',1), 
	('Chakunel','Profesional',1),
	('Chakunem','Profesionalidad',1), 
	('Chakunib��l','Instrumental',1), 
	('Chakunik','Trabajar',1), 
	('Champomanel nab�e ajpop, k�am�l b�e amaq�','Presidente de rep�blica',1), 
	('Chanim tz�ib�','Taquigraf�a',1),
	('Chanim, aninaq','Pronto',1), 
	('Chapab��l q�ab�','Anticipo',1), 
	('Chapanik, k�osk�otik','Tocar',1), 
	('Chapatalik','Detenido',1),
	('Chapb��l, tiqchapab��l','Gancho (de ropa)',1),
	('Chapik, chaponik, chaponem','Agarrar, tocar',1), 
	('Chapob�al, lajab�','Trampa',1), 
	('Chaponem','Agarrarlo',1),
	('Chaq�, nuchaq�','Hermana menor de mujer',1), 
	('Chaq�ajnaq','Cocido',1),
	('Chaq�ajrsan, tzakik','Cocer, cocido',1),
	('Chaq�ich�umil','Neptuno (planeta)',1),
	('Chaqi�j','Seco',1),
	('Chaqi�j chikop','Insecto',1), 
	('Chaqi�jarem, chaqi�jarik','Secar',1), 
	('Chaqi�jb��l','Deshidratante',1), 
	('Chaqi�jnem','Deshidrataci�n',1), 
	('Chaqi�jnik','Deshidratar',1), 
	('Chaqi�jq�ijol','Oto�o',1),
	('Chaqo�n','Ordinario (tosco, burdo)',1), 
	('Chaqon','Cosquilla',1),
	('Chaqonanem, chaqonanik','Hacer cosquillas',1), 
	('Chareb��l','Carruaje',1),
	('Charqajin ib�','Aterrizarse (de aviones, helic�pteros)',1), 
	('Charqajinem','Aterrizaje',1),
	('Charqajinik','Aterrizar',1),
	('Charyak ib�','Despegarse (de aviones, etc.)',1), 
	('Charyakinik','Despegar',1),
	('Chasacha numak','Perd�name, disc�lpame',1),
	('Chat�l wa�im','Dieta',1), 
	('Chatwaljoq','Lev�ntese',1), 
	('Chawila awib�','Cu�date',1), 
	('Chayunik, chayunem','Colar',1),
	('Che�','�rbol,madera, palo',1),
	('Che� tz�ib�ab��l','L�piz',1),
	('Che�tz�ajb��l','Cray�n de madera',1), 
	('Che�wkaq�iq�il','Troposfera',1),
	('Chet','Granero cuadrado',1), 
	('Chetechik','Plegado',1),
	('Chi la�','All�',1),
	('Chi pur','Jutiapa',1), 
	('Chi rech','A �l, ella',1), 
	('Chi rij',	'A tras de',1), 
	('Chi�aj','Boca',1), 
	('Chi�ch�, kupib�al, qupib��l, pusb��l','Cuchillo',1), 
	('Chi�ych�k','Fleco',1), 
	('Chib�, chib�cha�q','Helecho',1), 
	('Chij','Lana',1),
	('Chikb��l ja�, sutz�b��l ja','Rociador (spray',1),
	('Chikop, awaj','Animal, animal dom�stico',1), 
	('Chikopb��l','Zool�gico, jard�n zool�gico',1), 
	('Chikopil','Par�sito',1),
	('Chikopk�ajnem','Polinizaci�n entom�gama (por insectos)',1),
	('Chilb�ejnem, chilb�ej','Exhortaci�n, exhortar',1), 
	('Chim','Morral, bolsa, matate',1), 
	('Chimchikopib�	Marsupiales Chinab�jul','Huehuetenango',1), 
	('Chipaxukut, jeqxukut','Lado inicial',1),
	('Chipnem, majb��l , jeqb��l','Inicio',1), 
	('Chiq�ayes','Zacapa Chiquimula	Chiquimula',1),
	('Chirij kolonel','D.c.(despu�s de cristo)',1), 
	('Chirij','le, Afuera de',1),
	('Chirij, k�a te k�u ri�','Despu�s, detr�s de',1), 
	('Chirijja�j','Velo (paladar suave)',1), 
	('Chirijset','Metasfera',1),
	('Chirmi�y, su�','Chirim�a',1), 
	('Chitatab�ej ak�alab�','Atenci�n ni�os',1), 
	('Chitatb�ej','Escuchen',1), 
	('Chitzapij ichi, kixch�aw taj','Silencio',1),
	('Cho','Lago',1), 
	('Cho�kej, kumatz','Calambre',1),
	('Cho�l, jolojik, tuqutik','Flojo (ropa floja)',1), 
	('Cho�m','Camar�n',1),
	('Cho�pijat�inib��l','Desarmador (destornillador)',1),
	('Cho�pinik','Desenroscar',1), 
	('Chojj�b�','Diluvio',1), 
	('Chojoj atinib��l','Ducha',1), 
	('Chok�ok�, pok�opik','Tieso',1), 
	('Chokoyab��l','Formulario',1), 
	('Chokoyam','Formulado',1), 
	('Chokoyanem','Formulaci�n',1), 
	('Chokoyanik','Formular',1), 
	('Chokoyil','F�rmula',1),
	('Chol','Tabla (matem�tica o elementos b�sicos qu�micos)',1), 
	('Cholaj','Fila, hilera',1), 
	('Cholajil saqil','Receta',1),
	('Cholajilab��l','Sistema de numeraci�n',1), 
	('Cholajilanik','Contabilidad',1),
	('Cholb��l chak','Programa',1), 
	('Cholb��l tzij','Crucigrama',1), 
	('Cholb�inem','Desfile',1), 
	('Cholchak','Plan',1),
	('Cholchak tijonem, cholchakunik','	Planificaci�n educativa, planificar',1), 
	('Cholchi�','Comunidad ling��stica',1), 
	('Choletz�anem','Deporte',1),
	('Choljik�nem, ub�ek�i�alil','Ecuaci�n',1), 
	('Cholk�aslemal','Constitucionalidad',1),
	('Cholk�utub��l pam','Tabla de contenidos',1), 
	('Cholkejen ch�ich�','Ciclismo',1),
	('Cholkunel','Receta de comida',1), 
	('Cholkunub�al','Receta de medicamento',1), 
	('Chol�l tzij','Sintaxis',1),
	('Chololej','Ordenar',1), 
	('Cholpaxnel','M�ltiplo',1),
	('Cholq�ax','Programa (radiof�nico)',1),
	('Cholq�ax silow�ch','Programa (programa de televisi�n)',1), 
	('Cholq�axnem','Programaci�n (de televisi�n)',1), 
	('Cholse�tb�ix','Discoteca',1),
	('Choltijomb��l','Curr�culo',1), 
	('Choltijonem','Educaci�n formal',1), 
	('Choltz�ib�','Alfabeto',1), 
	('Choltz�ib�alil','Alfabetismo',1), 
	('Choltz�ib�anem, eta�man tz�ib�anik�','Alfabetizaci�n',1), 
	('Choltz�ib�anik','Alfabetizar',1), 
	('Choltzij, cholsuk�tzij, soltzij','Diccionario',1), 
	('Choluk�u�x chulb��l','Sistema urinario',1), 
	('Choluk�u�x ib�och�ib��l','Sistema nervioso',1),
	('Choluk�u�x kik�el','Sistema circulatorio',1), 
	('Choluk�u�x uxlab�al','Sistema respiratorio',1), 
	('Choluk�u�x wa�ikil','Sistema digestivo',1), 
	('Cholupam','Contenido',1),
	('Cholwachb��l','�lbum',1), 
	('Chom','Gordo',1), 
	('Chom nakalwos	Xen�n Chom su�, kaxla�n su�','Trompeta',1), 
	('Chomab��l','Pol�tica',1),
	('Chomab��l tzij','Pol�tica,ling��stica',1), 
	('Chomanem','Pensamiento',1), 
	('Chomanik','Pensar',1), 
	('Chomwiq�ab�','Dedo pulgar',1), 
	('Chomxko�l','Intestino grueso',1), 
	('Choqoje�, xuquje�','Tambi�n',1), 
	('Choyib�al','Machete',1),
	('Choyoj ajij','Zafra',1),
	('Chu','Hediondo',1), 
	('Chu wach','Ante',1), 
	('Chu�ab��j','Azufre',1), 
	('Chub�, nuchub�','Saliva',1), 
	('Chub�aj','Escupo',1), 
	('Chub�anem, chub�anik, chub�nik','Escupir',1), 
	('Chuch, nan','Mam�',1), 
	('Chuchi�','A la orilla de',1),
	('Chuchuxel','Se�ora principal',1), 
	('Chul ib� ch�ich�','Estroncio',1),
	('Chulaj','Orina, miado',1),
	('Chulb�al K�ajk��s','Aparato de Golg�',1), 
	('Chun','Cal',1),
	('Chupam','Adentro, dentro',1), 
	('Chupb��l q�aq�','Extintor',1), 
	('Chupb��l tz�ib�','Corrector',1),
	('Chupch�umil','Nova (astronom�a)',1), 
	('Chupchutik ab��j','Perla',1),
	('Chuplib��l','Flash',1), 
	('Chupulq�aq�','Luci�rnaga',1), 
	('Chupum','Apagado',1), 
	('Chupunem','Cesaci�n',1), 
	('Chupunik, chupunem','Apagar',1),
	('Chuq�ab� k�amaq�aq�','Resistencia el�ctrica',1), 
	('Chuq�ab�il','Energ�a',1),
	('Chuq�ab�il ulew','Abono',1), 
	('Chuq�ab�iwa, yab��l chuq�ab�il','Vitamina',1), 
	('Chuq�akik�el','Presi�n arterial',1),
	('Chutzal, chuxukut','Al lado de..., al reverso',1), 
	('Chuwach','Enfrente de',1),
	('Chuxe�','Debajo de ',1),
	('Chuxo�','Entre',1), 
	('Chuxukut, naqaj','Cerca de, cerca',1), 
	('Chwe�q	','Ma�ana',1), 
	('Chwimeq�ena�','Totonicap�n',1),
	('E are�','Ellos, ellas',1),
	('Echam','Cu�ado de mujer',1),	
	('Echanel, echanik','Poseedor, poseer',1), 
	('Echb��l amaq�','Patria',1),
	('Echkil','Egocentrismo',1),
	('Ek�','Pie de gallo, pata de gallo',1), 
	('Elaq��n wach','Pirater�a',1),
	('Elaq�om','Asaltante',1), 
	('Elem, elik','Salir',1),
	('Elesanem, elesanik, esaxik','Eliminar, quitar, sacar',1), 
	('Elik','Deserci�n',1),
	('Elk�ayij','Exportar',1), 
	('Elunimrisanem','Internacional',1), 
	('Elunimrisaxik','Internacionalizar',1),
	('Ema','Pero',1), 
	('Eqa�lenel','Agente',1), 
	('Eqa�n','Carga',1), 
	('Eqale�n, chak','Oficio, cargo',1), 
	('Eqanib��l','Mochila',1), 
	('Eqanib��l ch�ich�','Cami�n',1),
	('Eqanik, eqanem','Cargar (en la espalda)',1), 
	('Erab��l ja�','Cubeta',1),
	('Ereb��l','Flete',1), 
	('Erenem','Acarr�alo',1), 
	('Erenik, erenem','Acarrear',1), 
	('Esab��l wachb��l','C�mara',1),
	('Esalitzelatz�am','Plomo (elemento qu�mico)',1),
	('Esanem','Menos',1),
	('Esanem, k�amoj','Sustracci�n',1), 
	('Esb��l no�j','Experimento',1), 
	('Esb��l s�b�','Chimenea',1),
	('Estados Unidos de Am�rica','Estados Unidos de Am�rica',1), 
	('Eta�mab��l','Conocimiento',1),
	('Eta�mab�alil b�antzij','Ling��stica aplicada',1), 
	('Eta�mab�alil ja','Hidrolog�a',1), 
	('Eta�mab�alil jalwajast�q','F�sica',1),
	('Eta�mab�alil k�aslem','Biolog�a',1), 
	('Eta�mab�alil kab�raqan','Sismolog�a',1),
	('no�jb�anem','Ciencias Naturales y Tecnolog�a',1),
	('Eta�mab�alil kunub��l','Farmacolog�a',1),
	('Eta�mab�alil suqyab�il','Epidemiolog�a',1), 
	('Eta�mab�alil tz�aqatil jastaq','Qu�mica',1), 
	('Eta�mab�alil uwachulew','Geograf�a',1), 
	('Eta�mab�alil uxe�yab�il','Patolog�a',1), 
	('Eta�mab�alil winaqil','Sociolog�a',1), 
	('Eta�mab�alil winaqilal','Ciencias sociales',1), 
	('Eta�mab�alil winaqilitzij','Socioling��stica',1), 
	('Eta�mab�alil xkanul','Vulcanolog�a',1), 
	('Eta�mab�alil yab�anima�','Cardiolog�a',1),
	('Eta�makab�raqanel','Sism�logo',1), 
	('Eta�malil q�ab�ch�ab��l','Dialectolog�a',1), 
	('Eta�manem, janik�','Saber',1),
	('Eta�manik nuk�soltzij','Lexicologia',1),
	('Eta�manik, eta�manem','Aprender a aprender, conocer, saber',1), 
	('Eta�mariqonem','Competencias cognoscitivas',1), 
	('Eta�mb�alil chikopib�','Zoolog�a',1),
	('Eta�mb�alil no�j','Psicolog�a',1), 
	('Eta�mb�alil puqno�jib��l','Ingenier�a',1), 
	('Eta�mb�anik','Saber actuar',1), 
	('Etab��l','Medida',1),
	('Etab��l rech jast�q','Evaluaci�n de productos',1),
	('Etab��l jech�b�alil','Estad�stica',1), 
	('Etab��l q�aq�al','Term�metro',1), 
	('Etab�al q�ij, kajb�alil','Horario',1), 
	('Etab��l, etab��l eta�manik','Evaluaci�n',1), 
	('Etab�anik','Evaluar',1),
	('Etab�anik ri b�ijno�j eta�manik','Evaluar el conocimiento conceptual',1), 
	('Etab�anik ri no�jib��l eta�manik','Evaluar el conocimiento actitudinal',1), 
	('Etab�anik ri q�axno�j eta�manik','Evaluar el conocimiento procedimental',1), 
	('Etab�l rech q�axnem','Evaluaci�n de procesos',1),
	('Etal	Se�al, huella',1), 
	('Etal','S�mbolo',1),
	('Etal','C�digo',1),
	('Etal k�olompwaq','Cuenta de ahorros',1), 
	('Etal pwaqb��l','Cuenta bancaria',1), 
	('Etal tzij','C�digo ling��stico',1), 
	('Etalil','Simbolismo',1),
	('Etan ib�','Autoevaluaci�n',1), 
	('Etanem, etanik','Medir',1),
	('Etanib��l b�anoj','Reglamento',1), 
	('Etawosb��l','Bar�metro',1), 
	('Etb��l roqow','Ebull�metro',1), 
	('Etok�al','Metro (medida)',1), 
	('Etpaqalib��l','Alt�metro',1), 
	('Etzelal','Crueldad',1),
	('Etz�ab�a�l','Juguete',1), 
	('Etz�ab�alil','Figuras',1),
	('Etz�achak','Din�mica (animaci�n)',1), 
	('Etz�amaq�em','Juegos ol�mpicos',1), 
	('Etz�amb��l','Cancha',1),
	('Etz�anch�ekoj','Loter�a',1), 
	('Etz�anem','Juego',1),
	('Etz�anem uxlanb��l, oxlane','Recreo, juego, descanso',1), 
	('Etz�anem, etz�anik','Jugar',1),
	('Etz�anib��l, kikb��l','Estadio',1), 
	('Etz�k�yaqb��l','Tiro al blanco',1), 
	('Ewanik, ewanem','Esconder',1),
	('Eye�m k�aslemal','Esperanza de vida ',1),
	('Eyenik','Esperar',1),
	('Eyowal','Enojo, c�lera',1),
	('Ib�och�','Vena, nervios',1),
	('Ib�och� k�amatyo�jil','Tejido nervioso',1), 
	('Ib�och�il b�oq�och','Nervio �ptico',1), 
	('Ib�och�il xikin','Nervio auditivo',1),
	('Ib�oy','Armadillo',1),
	('Ichaj','Verduras, hierba',1), 
	('Ichajb��l , xoral tikb�al ichaj','Hortaliza',1),
	('Ij','Sarampi�n',1), 
	('Ija�','Semilla',1), 
	('Ija�b��l','Semillero',1),
    ('Ija�il','Descendiente',1),
	('Ik','Chile',1),
    ('Ik�','Luna, mes',1), 
	('Ik�ilal','Mensualidad',1),
	('Ikaj','Hacha',1),
    ('Ikan, ixpak�pan','Gallina ciega',1),
	('Ikaq�','Sobrino',1),
	('Ikim, Chuxe�','Abajo de',1),
    ('Ikiranik, ikiranem','Cargar (en la cabeza)',1),
	('Ikoq�ij','Venus',1),
    ('Ikox','Hongo',1),
    ('Ilb�al','Vista',1),
    ('Ilb��l ch�akul','Radiograf�a',1),
	('Ilb��l ij','Retrovisor',1),
	('Ilb��l n�j','Larga vista',1),
    ('Ilb�an','Acto (de la obra)',1),
    ('Ilb�anem','Actuaci�n',1), 
	('Ilb�anik','Actuar',1),
    ('Ilik','Mirar',1),
    ('Ilinem','Responsabilidad',1),
	('Ilk�asnak�','Microsc�pico',1),
	('Ilk�olb��l','Teatro (lugar)',1),
	('Ilom','Visto',1),
    ('Ilonb��l chak','Administraci�n',1),
	('Ilonel','Contralor',1),
	('Ilonel chak','Administrador',1),
	('Ilonem, ilonik','Ver',1),
    ('Iltz�ib�','Monitor (de computador)',1),
	('Ilw�ch, lemw�ch','Lentes (para ver mejor)',1),
	('Imam','Nieto (a)',1),
    ('Imu�t','Hierbamora, quilete',1),
    ('Imul','Conejo',1),
    ('In','Yo',1), 
    ('Inkane�y, ankane�y','Banano',1),
    ('Inoch�','Sombra (persona o animal)',1), 
	('Inup','Ceiba',1),
	('Iq�, uk�u�xal kaqiq�','Ox�geno',1), 
	('Iq�anem','Oxigenaci�n',1), 
	('Is','Camote',1), 
	('Isab�al','Izabal',1), 
	('Ismachi�','Barba, bigote',1),
	('Ismal','Pluma, pelo de animal',1),
	('Itz','Brujer�a',1),
	('Itzel','Demonio, diablo, maldad',1), 
	('Itzel kunab�al','Veneno',1),
	('Itzelal','Maldici�n',1), 
	('Iwir','Ayer',1),
	('Ix','Vosotros',1), 
	('Ixajyuq�','Monja',1),
	('Ixal chak','Trabajo juvenil',1), 
	('Ixatz�yaqb��l','Blusa',1),
	('Ixija�','�vulo',1), 
	('Ixija�b��l','Ovario',1), 
	('Ixim','Ma�z',1), 
	('Ixjut','Gusano',1),
	('Ixk�aq','Garra de animal',1), 
	('Ixk�aqaj','U�a',1),
	('Ixkanul, xkanul','Volc�n, colina cerro',1), 
	('Ixkolob�','Intestino',1),
	('Ixmatuq�','Tepocate',1), 
	('Ixmukur','Tortolito',1),
	('Ixnam','Cu�ada de hombre',1), 
	('Ixoq','Mujer',1),
	('Ix�q k�ulajil','Lesbiana',1), 
	('Ix�q k�r','Sirena',1),
	('Ixoqal','Femenino (g�nero)',1),
	('Ixoqil, wixoqil','Esposa',1), 
	('Ixpa�ch','Lagartija',1), 
	('Ixpeq','Sapo',1), 
	('Ixq�alel','Princesa',1),
	('Ixtun�y','Trompa de Falopio',1),
	('Ixtuq�, ixtutz�, ixt�o�r','Rana, renacuajo, tepocate, Ixtuxil	Tal�n, carca�al',1),
	('Iya','Peric�n Iyonem	Obstetricia',1),
	('I�om re','Suegros de hombre',1),
	('Jab�unem, jab�unik', 'Espejo', 2),
	('Jach', 'Perro', 2),
	('Jachak�, jachak�ij', 'Guardi�n', 2),
	('Jal�q�, jal�q�ij', 'M�sico', 2),
	('Jalb��l', 'Jard�n', 2),
	('Jalib��l', 'Templo', 2),
	('Jan', 'Sol', 2),
	('Janal', 'D�a', 2),
	('Jinam', 'Lago', 2),
	('Job�', 'Luz', 2),
	('Job� k�olib��l', 'Electricidad', 2),
	('Jolom', 'Tierra', 2),
	('Jolom k�i�k�, ch�uti�, maltyox', 'Planeta', 2),
	('Juyu�, juyub�al', 'Isla', 2),
	('Kamik', 'Fuego', 2),
	('Kanab��l', 'Bosque', 2),
	('Kaqchikel', 'Idioma', 2),
	('K�aq�ik�', 'P�jaro', 2),
	('K�aslemal', 'Tesoro', 2),
	('K�atb��l', 'Piedra', 2),
	('K�iche�', 'Pueblo', 2),
	('K�oqa�, k�oqab�al', 'Nube', 2),
	('K�umatz', 'Serpiente', 2),
	('K�utu�', 'Cuchillo', 2),
	('Lab��l', 'Flor', 2),
	('Lajuj', 'Gato', 2),
	('Lajuj k�utu�, ulew', 'Le�n', 2),
	('Lajuj pusaq', 'Tigre', 2),
	('Lak�ab', 'Estrella',2),
	('Lajuj chik�, tijox', 'Mariposa', 2),
	('Lajuj kaq�, ixim', 'Abeja', 2),
	('Lak�ta�, lak�ta� b�i�', 'Aire', 2),
	('Lal', 'Agua', 2),
	('Lal k�utu�, iktan', 'Tibur�n', 2),
	('Lal ik�, q�anil', 'Pez', 2),
	('Lal tijox', 'Delf�n', 2),
	('Lal qanil', 'Ballena', 2),
	('Lal taq�, lal taq�al', 'R�o', 2),
	('Lalun', 'Lluvia', 2),
	('Lalun ixim', 'Arco iris', 2),
	('Lalun k�i�k�', 'Tormenta', 2),
	('Lamaj', 'Nieve', 2),
	('Lamaj ilb�al', 'Pico de monta�a', 2),
	('Lamaj k�utu�', 'Avalancha', 2),
	('Lamaj taq�al', 'Glaciar', 2),
	('Lamaj tijox', 'Trineo', 2),
	('Lamaj kaq�', 'Esqu�', 2),
	('Lamaj chik�, lamaj ixim', 'Copos de nieve', 2),
	('Lamaj k�i�k�', 'Granizo', 2),
	('Lamaj k�an', 'Hielo', 2),
	('Lamaj paq�', 'Ventisca', 2),
	('Lamaj ixim', 'Fr�o', 2),
	('Lamaj k�aq�ik�', 'Viento', 2),
	('Lamaj lak�ta�', 'Nube de nieve', 2),
	('Lamaj lak�al', 'Tormenta de nieve', 2),
	('Lamaj ak�alb��l', 'Invierno', 2),
	('Lamaj kumatz', 'Avalancha de nieve', 2),
	('Lamaj sutb�inb��l', 'Pista de esqu�', 2),
	('Lamaj juyu�, lamaj juyub�al', 'Isla de hielo', 2),
	('Lamaj k�aq�, lamaj k�aq�ab�al', 'Bosque de nieve', 2),
	('Lamaj kaqchikel', 'Idioma de nieve', 2),
	('Lamaj k�oqa�, lamaj k�oqab�al', 'Nube de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Lamaj lak�ab', 'Estrella de nieve', 2),
	('Lamaj lak�ta� b�i�', 'Aire de nieve', 2),
	('Lamaj lal', 'Agua de nieve', 2),
	('Lamaj tijox', 'Mariposa de nieve', 2),
	('Lamaj kaq�', 'Abeja de nieve', 2),
	('Lamaj taq�', 'R�o de nieve', 2),
	('Lamaj lamajun', 'Lluvia de nieve', 2),
	('Lamaj ixim', 'Arco iris de nieve', 2),
	('Lamaj k�i�k�', 'Tormenta de nieve', 2),
	('Lamaj k�umatz', 'Serpiente de nieve', 2),
	('Lamaj k�utu�', 'Cuchillo de nieve', 2),
	('Lamaj lab��l', 'Flor de nieve', 2),
	('Lamaj lajuj', 'Gato de nieve', 2),
	('Mach', 'Sombra', 2),
	('Mal', 'Culebra', 2),
	('Man', 'Pavo', 2),
	('Mukul', 'Cerro', 2),
	('Nak�al', 'Ojo', 2),
	('Nawi', 'Sol', 2),
	('Nik�aj', 'Murci�lago', 2),
	('Nim', 'Cara', 2),
	('Nimak', 'R�o', 2),
	('Nimlaq�, xin�q�, q�u�, k�uxub�', 'Luz', 2),
	('Nimal', 'Diente', 2),
	('Nimja�', 'Tres', 2),
	('Nimja� k�i�k�', 'Galaxia', 2),
	('Nimja� lak�ab', 'Estrella de la ma�ana', 2),
	('Nimja� k�ak�al', 'Planeta Marte', 2),
	('Nimja� lak�ta�', 'Sol', 2),
	('Nimja� juyu�', 'Tierra', 2),
	('Nimja� tijox', 'Mariposa', 2),
	('Nimja� ixim', 'Ma�z', 2),
	('Nimja� chik�, nimja� ch�uti�', 'Mariposa', 2),
	('Nimja� kaq�, nimja� ixim', 'Abeja', 2),
	('Nimja� paq�', 'Huevo', 2),
	('Nimja� ik', 'Pescado', 2),
	('Nimja� kaq�ab�al', 'Murci�lago', 2),
	('Nimja� lamaj', 'Nieve', 2),
	('Nimja� lak�ab', 'Estrella de la tarde', 2),
	('Nimja� lak�ta� b�i�', 'Viento', 2),
	('Nimja� lal', 'Agua', 2),
	('Nimja� tijox', 'Mariposa de noche', 2),
	('Nimja� kaq�', 'Abeja de noche', 2),
	('Nimja� taq�', 'R�o de noche', 2),
	('Nimja� lamajun', 'Lluvia de noche', 2),
	('Nimja� ixim', 'Arco iris de noche', 2),
	('Nimja� k�i�k�', 'Tormenta de noche', 2),
	('Nimja� k�umatz', 'Serpiente de noche', 2),
	('Nimja� k�utu�', 'Cuchillo de noche', 2),
	('Nimja� lab��l', 'Flor de noche', 2),
	('Nimja� lajuj', 'Gato de noche', 2),
	('Nimja� lak�ab', 'Estrella de noche', 2),
	('Nimja� lak�ta� b�i�', 'Aire de noche', 2),
	('Nimja� lal', 'Agua de noche', 2),
	('Machik', 'Oscuridad', 2),
    ('Mutz�, mutz�ij', 'Cosecha', 2),
    ('Muk�ul', 'Monta�a', 2),
    ('Muk�ul nimak', 'R�o de monta�a', 2),
    ('Muk�ul lak�ab', 'Estrella de monta�a', 2),
    ('Muk�ul tijox', 'Mariposa de monta�a', 2),
    ('Muk�ul ixim', 'Ma�z de monta�a', 2),
    ('Muk�ul chik�, muk�ul ch�uti�', 'Mariposa de monta�a', 2),
    ('Muk�ul kaq�, muk�ul ixim', 'Abeja de monta�a', 2),
    ('Muk�ul paq�', 'Huevo de monta�a', 2),
    ('Muk�ul ik�', 'Pescado de monta�a', 2),
    ('Muk�ul kaq�ab�al', 'Murci�lago de monta�a', 2),
    ('Muk�ul lamaj', 'Nieve de monta�a', 2),
    ('Muk�ul lak�ta� b�i�', 'Viento de monta�a', 2),
    ('Muk�ul lal', 'Agua de monta�a', 2),
    ('Muk�ul tijox', 'Mariposa de monta�a', 2),
    ('Muk�ul taq�', 'R�o de monta�a', 2),
    ('Muk�ul lamajun', 'Lluvia de monta�a', 2),
    ('Muk�ul ixim', 'Arco iris de monta�a', 2),
    ('Muk�ul k�i�k�', 'Tormenta de monta�a', 2),
    ('Muk�ul k�umatz', 'Serpiente de monta�a', 2),
    ('Muk�ul k�utu�', 'Cuchillo de monta�a', 2),
    ('Muk�ul lab��l', 'Flor de monta�a', 2),
    ('Muk�ul lajuj', 'Gato de monta�a', 2),
    ('Muk�ul lak�ab', 'Estrella de monta�a', 2),
    ('Muk�ul lak�ta� b�i�', 'Aire de monta�a', 2),
    ('Muk�ul lal', 'Agua de monta�a', 2),
	('Oq�, oq�ij', 'Luz', 2), 
    ('Oq�ab�, oq�ab�al', 'Sombra', 2),
    ('Oq�al', 'Culebra', 2),
    ('Oq�ijal', 'Diente de le�n', 2),
    ('Oq�ij k�utu�', 'Cuchillo de luz', 2),
    ('Oq�ij tijox', 'Mariposa de luz', 2),
    ('Oq�ij ixim', 'Ma�z de luz', 2),
    ('Oq�ij chik�, oq�ij ch�uti�', 'Mariposa de luz', 2),
    ('Oq�ij kaq�, oq�ij ixim', 'Abeja de luz', 2),
    ('Oq�ij paq�', 'Huevo de luz', 2),
    ('Oq�ij ik�', 'Pescado de luz', 2),
    ('Oq�ij kaq�ab�al', 'Murci�lago de luz', 2),
    ('Oq�ij lamaj', 'Nieve de luz', 2),
    ('Oq�ij lak�ab', 'Estrella de luz', 2),
    ('Oq�ij lak�ta� b�i�', 'Viento de luz', 2),
    ('Oq�ij lal', 'Agua de luz', 2),
    ('Oq�ij tijox', 'Mariposa de luz', 2),
    ('Oq�ij taq�', 'R�o de luz', 2),
    ('Oq�ij lamajun', 'Lluvia de luz', 2),
    ('Oq�ij ixim', 'Arco iris de luz', 2),
    ('Oq�ij k�i�k�', 'Tormenta de luz', 2),
    ('Oq�ij k�umatz', 'Serpiente de luz', 2),
    ('Oq�ij k�utu�', 'Cuchillo de luz', 2),
    ('Oq�ij lab��l', 'Flor de luz', 2),
    ('Oq�ij lajuj', 'Gato de luz', 2),
    ('Oq�ij lak�ab', 'Estrella de luz', 2),
    ('Oq�ij lak�ta� b�i�', 'Aire de luz', 2),
    ('Oq�ij lal', 'Agua de luz', 2),
	('L�ch�, lach�ik�, chak, chak�l', 'Ni�o', 2),
    ('L�ch k�utu�, lach�ik k�utu�', 'Cuchillo de ni�o', 2),
    ('L�ch tijox', 'Mariposa de ni�o', 2),
    ('L�ch kaq�, lach�ik ixim', 'Abeja de ni�o', 2),
    ('L�ch paq�', 'Huevo de ni�o', 2),
    ('L�ch ik�', 'Pescado de ni�o', 2),
    ('L�ch kaq�ab�al', 'Murci�lago de ni�o', 2),
    ('L�ch lamaj', 'Nieve de ni�o', 2),
    ('L�ch lak�ab', 'Estrella de ni�o', 2),
    ('L�ch lak�ta� b�i�', 'Viento de ni�o', 2),
    ('L�ch lal', 'Agua de ni�o', 2),
    ('L�ch tijox', 'Mariposa de ni�o', 2),
    ('L�ch taq�', 'R�o de ni�o', 2),  
	('L�ch lamajun', 'Lluvia de ni�o', 2),
    ('L�ch ixim', 'Arco iris de ni�o', 2),
    ('L�ch k�i�k�', 'Tormenta de ni�o', 2),
    ('L�ch k�umatz', 'Serpiente de ni�o', 2),
    ('L�ch k�utu�', 'Cuchillo de ni�o', 2),
    ('L�ch lab��l', 'Flor de ni�o', 2),
    ('L�ch lajuj', 'Gato de ni�o', 2),
    ('L�ch lak�ab', 'Estrella de ni�o', 2),
    ('L�ch lak�ta� b�i�', 'Aire de ni�o', 2),
    ('L�ch lal', 'Agua de ni�o', 2),
    ('L�chun', 'Lluvia de ni�o', 2),
    ('L�ch ixim', 'Arco iris de ni�o', 2),
    ('L�ch k�i�k�', 'Tormenta de ni�o', 2),
    ('L�ch k�umatz', 'Serpiente de ni�o', 2),
    ('L�ch k�utu�', 'Cuchillo de ni�o', 2),
    ('L�ch lab��l', 'Flor de ni�o', 2),
    ('L�ch lajuj', 'Gato de ni�o', 2),
    ('L�ch lak�ab', 'Estrella de ni�o', 2),
    ('L�ch lak�ta� b�i�', 'Aire de ni�o', 2),
    ('L�ch lal', 'Agua de ni�o', 2),
	('P�w�', 'Luz', 2),
    ('Paxil', 'Sombra', 2),
    ('Pech', 'Perro', 2),
    ('Pechak�, pechak�ij', 'Guardi�n', 2),
    ('Pel', 'M�sico', 2),
    ('Pelb��l', 'Jard�n', 2),
    ('Pelib��l', 'Templo', 2),
    ('Pen', 'Sol', 2),
    ('Penal', 'D�a', 2),
    ('Pij', 'Lago', 2),
    ('Pob�', 'Luz', 2),
    ('Pob� k�olib��l', 'Electricidad', 2),
    ('Polom', 'Tierra', 2),
    ('Polom k�i�k�, ch�uti�, maltyox', 'Planeta', 2),
    ('Puyu�, puyub�al', 'Isla', 2),
    ('Pamik', 'Fuego', 2),
    ('Panab��l', 'Bosque', 2),
    ('Paqchikel', 'Idioma', 2),
    ('P�aq�ik�', 'P�jaro', 2),
    ('P�aslemal', 'Tesoro', 2),
    ('P�atb��l', 'Piedra', 2),
    ('P�iche�', 'Pueblo', 2),
    ('P�oqa�, p�oqab�al', 'Nube', 2),
    ('P�umatz', 'Serpiente', 2),
    ('P�utu�', 'Cuchillo', 2),
    ('P�ab��l', 'Flor', 2),
    ('P�ajuj', 'Gato', 2),
    ('P�ajuj k�utu�, ulew', 'Le�n', 2),
    ('P�ajuj pusaq', 'Tigre', 2),
    ('P�ak�ab', 'Estrella', 2),
    ('P�ajuj chik�, tijox', 'Mariposa', 2),
    ('P�ajuj kaq�, ixim', 'Abeja', 2),
    ('P�ak�ta�, p�ak�ta� b�i�', 'Aire', 2),
    ('Pal', 'Agua', 2),
    ('Pal k�utu�, iktan', 'Tibur�n', 2),
    ('Pal ik�, q�anil', 'Pez', 2),
    ('Pal tijox', 'Delf�n', 2),
    ('Pal qanil', 'Ballena', 2),
    ('Pal taq�, pal taq�al', 'R�o', 2),
    ('Palun', 'Lluvia', 2),
    ('Palun ixim', 'Arco iris', 2),
    ('Palun k�i�k�', 'Tormenta', 2),
    ('Pamaj', 'Nieve', 2),
    ('Pamaj ilb�al', 'Pico de monta�a', 2),
    ('Pamaj k�utu�', 'Avalancha', 2),
    ('Pamaj taq�al', 'Glaciar', 2),
    ('Pamaj tijox', 'Trineo', 2),
    ('Pamaj kaq�', 'Esqu�', 2),
    ('Pamaj chik�, pamaj ixim', 'Copos de nieve', 2),
    ('Pamaj k�i�k�', 'Granizo', 2),
    ('Pamaj k�an', 'Hielo', 2),
    ('Pamaj paq�', 'Ventisca', 2),
    ('Pamaj ixim', 'Fr�o', 2),
    ('Pamaj k�aq�ik�', 'Viento', 2),
    ('Pamaj lak�ta�', 'Nube de nieve', 2),
    ('Pamaj lak�al', 'Tormenta de nieve', 2),
    ('Pamaj ak�alb��l', 'Invierno', 2),
    ('Pamaj kumatz', 'Avalancha de nieve', 2),
    ('Pamaj sutb�inb��l', 'Pista de esqu�', 2),
    ('Pamaj juyu�, pamaj juyub�al', 'Isla de hielo', 2),
    ('Pamaj k�aq�, pamaj k�aq�ab�al', 'Bosque de nieve', 2),
    ('Pamaj kaqchikel', 'Idioma de nieve', 2),
    ('Pamaj k�oqa�, pamaj k�oqab�al', 'Nube de nieve', 2),
    ('Pamaj k�utu�', 'Cuchillo de nieve', 2),
    ('Pamaj lab��l', 'Flor de nieve', 2),
    ('Pamaj lajuj', 'Gato de nieve', 2),
    ('Pamaj lak�ab', 'Estrella de nieve', 2),
    ('Pamaj lak�ta� b�i�', 'Aire de nieve', 2),
    ('Pamaj lal', 'Agua de nieve', 2),
    ('Pamaj tijox', 'Mariposa de nieve', 2),
    ('Pamaj kaq�', 'Abeja de nieve', 2),
    ('Pamaj taq�', 'R�o de nieve', 2),
    ('Pamaj pamajun', 'Lluvia de nieve', 2),
    ('Pamaj ixim', 'Arco iris de nieve', 2),
    ('Pamaj k�i�k�', 'Tormenta de nieve', 2),
    ('Pamaj k�umatz', 'Serpiente de nieve', 2),
    ('Pamaj k�utu�', 'Cuchillo de nieve', 2),
    ('Pamaj lab��l', 'Flor de nieve', 2),
    ('Pamaj lajuj', 'Gato de nieve', 2),
    ('Pamaj lak�ab', 'Estrella de nieve', 2),
    ('Pamaj lak�ta� b�i�', 'Aire de nieve', 2),
    ('Pamaj lal', 'Agua de nieve', 2),
	('Q�ch�, qach�ik�, chak, chak�l', 'Ni�o', 2),
    ('Q�ch k�utu�, qach�ik k�utu�', 'Cuchillo de ni�o', 2),
    ('Q�ch tijox', 'Mariposa de ni�o', 2),
    ('Q�ch kaq�, qach�ik ixim', 'Abeja de ni�o', 2),
    ('Q�ch paq�', 'Huevo de ni�o', 2),
    ('Q�ch ik�', 'Pescado de ni�o', 2),
    ('Q�ch kaq�ab�al', 'Murci�lago de ni�o', 2),
    ('Q�ch lamaj', 'Nieve de ni�o', 2),
    ('Q�ch lak�ab', 'Estrella de ni�o', 2),
    ('Q�ch lak�ta� b�i�', 'Viento de ni�o', 2),
    ('Q�ch lal', 'Agua de ni�o', 2),
    ('Q�ch tijox', 'Mariposa de ni�o', 2),
    ('Q�ch taq�', 'R�o de ni�o', 2),
    ('Q�ch lamajun', 'Lluvia de ni�o', 2),
    ('Q�ch ixim', 'Arco iris de ni�o', 2),
    ('Q�ch k�i�k�', 'Tormenta de ni�o', 2),
    ('Q�ch k�umatz', 'Serpiente de ni�o', 2),
    ('Q�ch k�utu�', 'Cuchillo de ni�o', 2),
    ('Q�ch lab��l', 'Flor de ni�o', 2),
    ('Q�ch lajuj', 'Gato de ni�o', 2),
    ('Q�ch lak�ab', 'Estrella de ni�o', 2),
    ('Q�ch lak�ta� b�i�', 'Aire de ni�o', 2),
    ('Q�ch lal', 'Agua de ni�o', 2),
    ('Q�chun', 'Lluvia de ni�o', 2),
    ('Q�ch ixim', 'Arco iris de ni�o', 2),
    ('Q�ch k�i�k�', 'Tormenta de ni�o', 2),
    ('Q�ch k�umatz', 'Serpiente de ni�o', 2),
    ('Q�ch k�utu�', 'Cuchillo de ni�o', 2),
    ('Q�ch lab��l', 'Flor de ni�o', 2),
    ('Q�ch lajuj', 'Gato de ni�o', 2),
    ('Q�ch lak�ab', 'Estrella de ni�o', 2),
    ('Q�ch lak�ta� b�i�', 'Aire de ni�o', 2),
    ('Q�ch lal', 'Agua de ni�o', 2),
	('R�w�', 'Luz', 2),
    ('Raxil', 'Sombra', 2),
    ('Rech', 'Perro', 2),
    ('Rechak�, rechak�ij', 'Guardi�n', 2),
    ('Rel', 'M�sico', 2),
    ('Relb��l', 'Jard�n', 2),
    ('Relib��l', 'Templo', 2),
    ('Ren', 'Sol', 2),
    ('Renal', 'D�a', 2),
    ('Rij', 'Lago', 2),
    ('Rob�', 'Luz', 2),
    ('Rob� k�olib��l', 'Electricidad', 2),
    ('Rolom', 'Tierra', 2),
    ('Rolom k�i�k�, ch�uti�, maltyox', 'Planeta', 2),
    ('Ruyu�, ruyub�al', 'Isla', 2),
    ('Ramik', 'Fuego', 2),
    ('Ranab��l', 'Bosque', 2),
    ('Raqchikel', 'Idioma', 2),
    ('R�aq�ik�', 'P�jaro', 2),
    ('R�aslemal', 'Tesoro', 2),
    ('R�atb��l', 'Piedra', 2),
    ('R�iche�', 'Pueblo', 2),
    ('R�oqa�, r�oqab�al', 'Nube', 2),
    ('R�umatz', 'Serpiente', 2),
    ('R�utu�', 'Cuchillo', 2),
    ('R�ab��l', 'Flor', 2),
    ('R�ajuj', 'Gato', 2),
    ('R�ajuj k�utu�, ulew', 'Le�n', 2),
    ('R�ajuj pusaq', 'Tigre', 2),
    ('R�ak�ab', 'Estrella', 2),
    ('R�ajuj chik�, tijox', 'Mariposa', 2),
    ('R�ajuj kaq�, ixim', 'Abeja', 2),
    ('R�ak�ta�, r�ak�ta� b�i�', 'Aire', 2),
    ('Ral', 'Agua', 2),
    ('Ral k�utu�, iktan', 'Tibur�n', 2),
    ('Ral ik�, q�anil', 'Pez', 2),
    ('Ral tijox', 'Delf�n', 2),
    ('Ral qanil', 'Ballena', 2),
    ('Ral taq�, ral taq�al', 'R�o', 2),-
    ('Ralun', 'Lluvia', 2),
    ('Ralun ixim', 'Arco iris', 2),
    ('Ralun k�i�k�', 'Tormenta', 2),
    ('Ramaj', 'Nieve', 2),
    ('Ramaj ilb�al', 'Pico de monta�a', 2),
    ('Ramaj k�utu�', 'Avalancha', 2),
    ('Ramaj taq�al', 'Glaciar', 2),
    ('Ramaj tijox', 'Trineo', 2),
    ('Ramaj kaq�', 'Esqu�', 2),
    ('Ramaj chik�, ramaj ixim', 'Copos de nieve', 2),
    ('Ramaj k�i�k�', 'Granizo', 2),
    ('Ramaj k�an', 'Hielo', 2),
    ('Ramaj paq�', 'Ventisca', 2),
    ('Ramaj ixim', 'Fr�o', 2),
    ('Ramaj k�aq�ik�', 'Viento', 2),
    ('Ramaj lak�ta�', 'Nube de nieve', 2),
    ('Ramaj lak�al', 'Tormenta de nieve', 2),
    ('Ramaj ak�alb��l', 'Invierno', 2),
    ('Ramaj kumatz', 'Avalancha de nieve', 2),
    ('Ramaj sutb�inb��l', 'Pista de esqu�', 2),
    ('Ramaj juyu�, ramaj juyub�al', 'Isla de hielo', 2),
    ('Ramaj k�aq�, ramaj k�aq�ab�al', 'Bosque de nieve', 2),
    ('Ramaj kaqchikel', 'Idioma de nieve', 2),
    ('Ramaj k�oqa�, ramaj k�oqab�al', 'Nube de nieve', 2),
    ('Ramaj k�utu�', 'Cuchillo de nieve', 2),
    ('Ramaj lab��l', 'Flor de nieve', 2),
    ('Ramaj lajuj', 'Gato de nieve', 2),
    ('Ramaj lak�ab', 'Estrella de nieve', 2),
    ('Ramaj lak�ta� b�i�', 'Aire de nieve', 2),
    ('Ramaj lal', 'Agua de nieve', 2),
    ('Ramaj tijox', 'Mariposa de nieve', 2),
    ('Ramaj kaq�', 'Abeja de nieve', 2),
    ('Ramaj taq�', 'R�o de nieve', 2),
    ('Ramaj ramajun', 'Lluvia de nieve', 2),
    ('Ramaj ixim', 'Arco iris de nieve', 2),
    ('Ramaj k�i�k�', 'Tormenta de nieve', 2),
    ('Ramaj k�umatz', 'Serpiente de nieve', 2),
    ('Ramaj k�utu�', 'Cuchillo de nieve', 2),
    ('Ramaj lab��l', 'Flor de nieve', 2),
    ('Ramaj lajuj', 'Gato de nieve', 2),
    ('Ramaj lak�ab', 'Estrella de nieve', 2),
    ('Ramaj lak�ta� b�i�', 'Aire de nieve', 2),
    ('Ramaj lal', 'Agua de nieve', 2),
	('S�w�', 'Luz', 2),
    ('Saxil', 'Sombra', 2),
    ('Sech', 'Perro', 2),
    ('Sechak�, sechak�ij', 'Guardi�n', 2),
    ('Sel', 'M�sico', 2),
    ('Selb��l', 'Jard�n', 2),
    ('Selib��l', 'Templo', 2),
    ('Sen', 'Sol', 2),
    ('Senal', 'D�a', 2),
    ('Sij', 'Lago', 2),
    ('Sob�', 'Luz', 2),
    ('Sob� k�olib��l', 'Electricidad', 2),
    ('Solom', 'Tierra', 2),
    ('Solom k�i�k�, ch�uti�, maltyox', 'Planeta', 2),
    ('Suyu�, suyub�al', 'Isla', 2),
    ('Samik', 'Fuego', 2),
    ('Sanab��l', 'Bosque', 2),
    ('Saqchikel', 'Idioma', 2),
    ('S�aq�ik�', 'P�jaro', 2),
    ('S�aslemal', 'Tesoro', 2),
    ('S�atb��l', 'Piedra', 2),
    ('S�iche�', 'Pueblo', 2),
    ('S�oqa�, s�oqab�al', 'Nube', 2),
    ('S�umatz', 'Serpiente', 2),
    ('S�utu�', 'Cuchillo', 2),
    ('S�ab��l', 'Flor', 2),
    ('S�ajuj', 'Gato', 2),
    ('S�ajuj k�utu�, ulew', 'Le�n', 2),
    ('S�ajuj pusaq', 'Tigre', 2),
    ('S�ak�ab', 'Estrella', 2),
    ('S�ajuj chik�, tijox', 'Mariposa', 2),
    ('S�ajuj kaq�, ixim', 'Abeja', 2),
    ('S�ak�ta�, s�ak�ta� b�i�', 'Aire', 2),
    ('Sal', 'Agua', 2),
    ('Sal k�utu�, iktan', 'Tibur�n', 2),
    ('Sal ik�, q�anil', 'Pez', 2),
    ('Sal tijox', 'Delf�n', 2),
    ('Sal qanil', 'Ballena', 2),
    ('Sal taq�, sal taq�al', 'R�o', 2),
    ('Salun', 'Lluvia', 2),
    ('Salun ixim', 'Arco iris', 2),
    ('Salun k�i�k�', 'Tormenta', 2),
    ('Samaj', 'Nieve', 2),
    ('Samaj ilb�al', 'Pico de monta�a', 2),
    ('Samaj k�utu�', 'Avalancha', 2),
    ('Samaj taq�al', 'Glaciar', 2),
    ('Samaj tijox', 'Trineo', 2),
    ('Samaj kaq�', 'Esqu�', 2),
    ('Samaj chik�, samaj ixim', 'Copos de nieve', 2),
    ('Samaj k�i�k�', 'Granizo', 2),
    ('Samaj k�an', 'Hielo', 2),
    ('Samaj paq�', 'Ventisca', 2),
    ('Samaj ixim', 'Fr�o', 2),
    ('Samaj k�aq�ik�', 'Viento', 2),
    ('Samaj lak�ta�', 'Nube de nieve', 2),
    ('Samaj lak�al', 'Tormenta de nieve', 2),
    ('Samaj ak�alb��l', 'Invierno', 2),
    ('Samaj kumatz', 'Avalancha de nieve', 2),
    ('Samaj sutb�inb��l', 'Pista de esqu�', 2),
    ('Samaj juyu�, samaj juyub�al', 'Isla de hielo', 2),
    ('Samaj k�aq�, samaj k�aq�ab�al', 'Bosque de nieve', 2),
    ('Samaj kaqchikel', 'Idioma de nieve', 2),
    ('Samaj k�oqa�, samaj k�oqab�al', 'Nube de nieve', 2),
    ('Samaj k�utu�', 'Cuchillo de nieve', 2),
    ('Samaj lab��l', 'Flor de nieve', 2),
    ('Samaj lajuj', 'Gato de nieve', 2),
    ('Samaj lak�ab', 'Estrella de nieve', 2),
    ('Samaj lak�ta� b�i�', 'Aire de nieve', 2),
    ('Samaj lal', 'Agua de nieve', 2),
	('Taqal', 'Tierra', 2),
	('Tz�utujil', 'Idioma', 2),
	('Tz�utujil jaqal', 'Territorio', 2),
	('Tz�utujil xonaqal', 'Pa�s', 2),
	('Ub�anik', 'Ense�ar', 2),
	('Uk�itunem', 'Romper', 2),
	('Ulew', 'Cielo', 2),
	('Ulew winaq', 'Estrella', 2),
	('Taq', 'Piedra', 2),
	('Taqab�, taq�, taqatz�, tzuktz�, tz�i�, tzak�ik�, tzakal', 'Animales', 2),
	('Tz�a�, tz�it�, tz�ik�ab�, tz�ununij', 'Insectos', 2),
	('Tz�aq', 'Culebra', 2),
	('Tz�aqon', 'Serpiente', 2),
	('Tz�ikin', 'P�jaro', 2),
	('Tz�ikin jaqal', 'Nido', 2),
	('Tz�oq', 'Buitre', 2),
	('Tz�ut', 'Lengua', 2),
	('Tz�utujil winaq', 'Persona', 2),
	('Tz�utujil q�anil', 'Comunidad', 2)
	('Tz�utujil ajaw', 'L�der', 2),
	('Tz�utujil tzikin', 'Ave', 2),
	('Tz�utujil winaq tz�a�, tz�i�, tzak�ik�, tzakal', 'Gente de la Tierra', 2),
	('Tz�ununij', 'Mariposa', 2),
	('Tz�ununij jaqal', 'Jard�n', 2),
	('Tz�ununij winaq', 'Mariposero', 2),
	('Tz�ununij tz�i�, tzak�ik�', 'Polilla', 2),
	('Tz�ununij tzikin', 'Mariposa nocturna', 2),
	('Tz�ununij tzakal', 'Mariposa diurna', 2),
	('Tz�ununij winaq tz�a�', 'Observador de mariposas', 2),
	('Tz�ununij q�umarkaj', 'Mariposa monarca', 2),
	('Tz�ununij winaq tz�a� tz�i�', 'Lepidopterista', 2),
	('Tz�ununij winaq tz�a� tzakal', 'Entom�logo', 2),
	('Tz�ununij ajaw', 'Mariposa reina', 2),
	('Tz�ununij ajaw tzikin', 'Mariposa monarca', 2),
	('Tz�ununij ajaw tzakal', 'Mariposa reina', 2),
	('Tz�ununij ajaw winaq tz�a� tz�i�', 'Entom�loga', 2),
	('Tz�ununij ajaw winaq tz�a� tzakal', 'Amante de las mariposas', 2),
	('Tz�ununij ajaw tz�a�', 'Naturaleza', 2),
	('Tz�ununij ajaw tz�a� tz�i�, tzak�ik�', 'Ecosistema', 2),
	('Tz�ununij ajaw tz�a� tzikin', 'Biodiversidad', 2),
	('Tz�ununij ajaw tz�a� tzakal', 'Conservaci�n', 2),
	('Tz�ununij ajaw winaq tz�a� tz�i�, tzak�ik�', 'Sostenibilidad', 2),
	('Tz�ununij ajaw winaq tz�a� tzakal', 'Ecolog�a', 2),
	('Tz�ununij ajaw winaq tz�a� tzakal', 'Preservaci�n', 2),
	('Tz�ununij ajaw winaq tz�a� tzikin', 'Restauraci�n', 2),
	('Tz�ununij ajaw winaq tz�a� tz�i�', 'Educaci�n ambiental', 2),
	('Tz�ununij ajaw winaq tz�a� tzak�ik�', 'Cuidado del medio ambiente', 2),
	('Tz�ununij ajaw winaq tz�a� tz�i�', 'Conciencia ambiental', 2),
	('Tz�ununij ajaw winaq tz�a� tzakal', 'Reciclaje', 2),
	('Tz�ununij ajaw winaq tz�a� tzakal', 'Sustentabilidad', 2),
	('U', 'Agua', 2),
	('Ub�anel', 'Despierto', 2),
	('Uk�u�, uk�u�aj', 'Romper', 2),
	('Uk�ub�, uk�ub�aj', 'Erosionar', 2),
	('Uk�ul', 'Saltar', 2),
	('Uk�ut, uk�utaj', 'Volar', 2),
	('Uk�utem', 'Flotar', 2),
	('Uk�ux, uk�uxaj', 'Hundir', 2),
	('Uk�uy, uk�uyaj', 'Moler', 2),
	('Uk�uyem', 'Masticar', 2),
	('Ul, ulaj', 'Ver', 2),
	('Ul�u�, ul�u�aj', 'So�ar', 2),
	('Ulej', 'Mirar', 2),
	('Ulem', 'Observar', 2),
	('Ulub�, ulub�aj', 'Esconder', 2),
	('Uluw, uluwaj', 'Re�r', 2),
	('Umuq, umuqaj', 'Ladrar', 2),
	('Unen', 'Oler', 2),
	('Uq�, uq�aj', 'Escuchar', 2),
	('Uq�ub�, uq�ub�aj', 'Palpar', 2),
	('Uq�ul', 'Girar', 2),
	('Uq�ut, uq�utaj', 'Empujar', 2),
	('Uq�uy, uq�uyaj', 'Abrir', 2),
	('Uq�uyem', 'Destapar', 2),
	('Ur, uraj', 'Gritar', 2),
	('Urub�, urub�aj', 'Aullar', 2),
	('Ut, utaj', 'Comer', 2),
	('Utem', 'Beber', 2),
	('Utz, utzaj', 'Caminar', 2),
	('Utzuk, utzukaj', 'Andar', 2),
	('Utzul, utzulaj', 'Correr', 2),
	('Utzum, utzumaj', 'Nadar', 2),
	('Utzunem', 'Bailar', 2),
	('Utzut, utzutaj', 'Saltar', 2),
	('Utz�ut, utz�utaj', 'Volar', 2),
	('Utz�utem', 'Flotar', 2),
	('Utz�ux, utz�uxaj', 'Hundir', 2),
	('Utz�uy, utz�uyaj', 'Moler', 2),
	('Utz�uyem', 'Masticar', 2),
	('Ul, ulaj', 'Ver', 2),
	('Ul�u�, ul�u�aj', 'So�ar', 2),
	('Ulej', 'Mirar', 2),
	('Ulem', 'Observar', 2),
	('Ulub�, ulub�aj', 'Esconder', 2),
	('Uluw, uluwaj', 'Re�r', 2),
	('Umuq, umuqaj', 'Ladrar', 2),
	('Unen', 'Oler', 2),
	('Uq�, uq�aj', 'Escuchar', 2),
	('Uq�ub�, uq�ub�aj', 'Palpar', 2),
	('Uq�ul', 'Girar', 2),
	('Vak�ab�','Tiembla', 2),
	('Vak�axik�', 'Brilla', 2),
	('Vak�ixik�','Relincha', 2),
	('Vak�oq�','Ri�e', 2),
	('Vak�oq�el, vak�oq�em', 'Ri�ndose', 2),
	('Vak�uq�', 'Ve', 2),
	('Vak�uq�em', 'Viendo', 2),
	('Vak�uxik�', 'Mira', 2),
	('Vak�uyik�', 'Muestra', 2),
	('Vak�ub�aq','Empieza', 2),
	('Vak�alb��l', 'Entra', 2),
	('Vak�alik�', 'Anuncia', 2),
	('Vak�atz�aj', 'Lee', 2),
	('Vak�ik�aj', 'Escribe', 2),
	('Vak�atz�i�', 'Instruye', 2),
	('Vak�alq�ij', 'Charla', 2),
	('Vak�oqil', 'Explica', 2),
	('Vak�ol', 'Conversa', 2),
	('Vak�oq�', 'Discute', 2),
	('Vak�i�', 'Argumenta', 2),
	('Vak�oraj', 'Debate', 2),
	('Vak�ik�aj', 'Confronta', 2),
	('Vak�ol', 'Negocia', 2),
	('Vak�olq�ij', 'Comparte', 2),
	('Vak�uq�aj', 'Colabora', 2),
	('Vak�utz�aj', 'Coopera', 2),
	('Vak�utaj', 'Ayuda', 2),
	('Vak�uyaj', 'Apoya', 2),
	('Vak�uyem', 'Facilita', 2),
	('Vak�uq�aj', 'Trabaja', 2),
	('Vak�ulaj', 'Resuelve', 2),
	('Vak�ulq�ij', 'Crea', 2),
	('Vak�ulik�aj', 'Innova', 2),
	('Vak�ub�aj', 'Dise�a', 2),
	('Vak�ib�al', 'Produce', 2),
	('Vak�ib�alaj', 'Fabrica', 2),
	('Vak�ib�ik�aj', 'Construye', 2),
	('Vak�ib�ulaj', 'Crea', 2),
	('Vak�ib�aq', 'Inicia', 2),
	('Vak�alb��l', 'Orfanato', 2),
	('Wa�', 'Pasar', 2),
	('Waq', 'Caminar', 2),
	('Waq�ol', 'Mover', 2),
	('Waq�um', 'Volar', 2),
	('Waq�ut', 'Saltar', 2),
	('Waq�uy', 'Correr', 2),
	('Waq�uyem', 'Huir', 2),
	('Waqib�', 'Ayudar', 2),
	('Waqik�aj', 'Guiar', 2),
	('Waqik�em', 'Guiando', 2),
	('Waqik�el', 'Gu�a', 2),
	('Waqik�oq', 'Guiado', 2),
	('Waqik�oqel', 'Gu�a', 2),
	('Waqik�um', 'Guiando', 2),
	('Waq�araj', 'Cosecha', 2),
	('Waq�olaj', 'Fuma', 2),
	('Waq�oq', 'Tose', 2),
	('Waq�oq�aj', 'Tos', 2),
	('Waq�oq�el', 'Tos', 2),
	('Waq�oq�oq', 'Tose', 2),
	('Waq�uq�', 'Busca', 2),
	('Waq�uq�aj', 'B�squeda', 2),
	('Waq�uq�el', 'B�squeda', 2),
	('Waq�uq�oq', 'Busca', 2),
	('Waq�uxik�', 'Mira', 2),
	('Waq�uyik�', 'Muestra', 2),
	('Waq�uyik�em', 'Mostrando', 2),
	('Waq�uyik�el', 'Muestra', 2),
	('Waq�uyik�oq', 'Muestra', 2),
	('Waq�uyem', 'Muestra', 2),
	('Waq�uyemem', 'Mostrando', 2),
	('Waq�uyel', 'Muestra', 2),
	('Waq�uyoq', 'Muestra', 2),
	('Waq�ub�', 'Dise�a', 2),
	('Waq�ub�aj', 'Dise�ador', 2),
	('Waq�ub�el', 'Dise�o', 2),
	('Waq�ub�oq', 'Dise�a', 2),
	('Waq�ub�oqel', 'Dise�o', 2),
	('Waq�ub�um', 'Dise�ando', 2),
	('Waq�ub�umel', 'Dise�ador', 2),
	('Waq�ib�al', 'Produce', 2),
	('Waq�ib�alaj', 'Fabrica', 2),
	('Waq�ib�ik�aj', 'Construye', 2),
	('Waq�ib�ulaj', 'Crea', 2),
	('Waq�ib�aq', 'Inicia', 2),
	('Waq�alb��l', 'Orfanato', 2),
	('Waq�atz�em', 'Aprende', 2),
	('Waq�atz�emem', 'Aprendiendo', 2),
	('Waq�atz�el', 'Aprender', 2),
	('Waq�atz�oq', 'Aprende', 2),
	('Xa', 'Desvalorativa', 2),
	('Xa chi je wi', 'Siempre es as�', 2),
	('Xajab�', 'Caite, zapato', 2),
	('Xaj�b� b�inb��l', 'Pat�n, patineta', 2),
	('Xajoj nimachi', 'Gigante (danza)', 2),
	('Xajoj, xojoj', 'Baile, danza', 2),
	('Xak�ab�', 'Brazada', 2),
	('Xalq�at', 'Cruz', 2),
	('Xalq�at b�e', 'Cruce', 2),
	('Xalq�at juch�', 'Coordenadas cartesianas', 2),
	('Xan', 'Adobe, pared', 2),
	('Xan ab�aj', 'Bloc', 2),
	('Xanab��j', 'Adoqu�n', 2),
	('Xantz�ajb��l', 'Acuarela', 2),
	('Xaq', 'Tizne', 2),
	('Xaq k�a te�', 'De repente', 2),
	('Xaq tz�ib�, jujunal tz�ib�', 'Letra de molde', 2),
	('Xaq, uxaq', 'Hoja', 2),
	('Yab�ab� ch�ich�', 'Amortiguador', 2),
	('Yab�il', 'Enfermedad', 2),
	('Yab�waram', 'Somnolencia', 2),
	('Yab�yoj', 'Discapacitados', 2),
	('Yajo9nem, yajonik', 'Rega�ar', 2),
	('Yak', 'Gato de monte', 2),
	('Yakal tze�', 'Chistoso, divertido', 2),
	('Yakatajem, yakatajik', 'Levantar', 2),
	('Yakb��l ch�ich�', 'Trique (para cambiar llantas)', 2),
	('Yak�l tze�', 'C�mico', 2),
	('Ya�al ub�ixik', 'Maestro de ceremonia', 2),
	('Ya�b��l kaq�iq�', 'Inflador', 2),
	('Ya�b��l q�aq�', 'L�mpara', 2),
	('Ya�ik uwi�', 'M�s', 2),
	('Ya�ik, ya�onem, ya�onik', 'Dar', 2),
	('Ya�ltajkil', 'Procesador', 2),
	('Ya�ltze�', 'Chiste', 2),
	('Ya�ltzijol', 'Campa�a �pol�tica�', 2),
	('Ya�ltzijolil', 'Publicidad', 2),
	('Ya�talil', 'Derecho', 2),
	('Ya�talil Alaxik', 'Derechos de la Familia', 2),
	('Ya�talil Tinamit', 'Derechos de los Pueblos', 2),
	('Ya�talil Winaqilal', 'Derechos Humanos', 2),
	('Y�oxmin', 'Mitosis', 2);
	








	
	



